#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Nov 04 14:45:44 CST 2022
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim DACx311_auto_set_behav -key {Behavioral:sim_1:Functional:DACx311_auto_set} -tclbatch DACx311_auto_set.tcl -protoinst "protoinst_files/bd_31bd.protoinst" -protoinst "protoinst_files/bd_c0fd.protoinst" -protoinst "protoinst_files/system.protoinst" -log simulate.log"
xsim DACx311_auto_set_behav -key {Behavioral:sim_1:Functional:DACx311_auto_set} -tclbatch DACx311_auto_set.tcl -protoinst "protoinst_files/bd_31bd.protoinst" -protoinst "protoinst_files/bd_c0fd.protoinst" -protoinst "protoinst_files/system.protoinst" -log simulate.log

